# Generated by Django 5.2.12 on 2026-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='pollshare',
            constraint=models.UniqueConstraint(fields=('poll',), name='unique_poll_share'),
        ),
    ]
