# Generated by Django 5.2.12 on 2026-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0004_alter_vote_unique_together_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_vote_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
